import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 60 }
padding = { x = 12, y = 8 }
decorations = "None"

[font]
normal = { family = "Hack", style = "Regular" }
size = 12

[keyboard]
bindings = [
  { key = "Q", mods = "Control", action = "Quit" }
]
